<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.7.0.5276" />
    <PackageReference Include="Emgu.CV.runtime.mini.ubuntu-x64" Version="4.7.0.5276" />
    <PackageReference Include="Emgu.CV.runtime.ubuntu-x64" Version="4.7.0.5276" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.7.0.5276" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.18" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PKMGerejaEbenhaezer.DataAccess\PKMGerejaEbenhaezer.DataAccess.csproj" />
    <ProjectReference Include="..\PKMGerejaEbenhaezer.Domain\PKMGerejaEbenhaezer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="img\" />
    <Folder Include="Models\PengumumanModels\" />
    <Folder Include="Models\WartaJemaatModels\" />
    <Folder Include="pdf\" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
