// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PKMGerejaEbenhaezer.DataAccess.Data;

#nullable disable

namespace PKMGerejaEbenhaezer.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240807091635_TambahPathFotoSmallMediumLarge")]
    partial class TambahPathFotoSmallMediumLarge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUserTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastChanged = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "AQAAAAIAAYagAAAAEAaPXuJHksi/2ecjkd5nhKTbxSu3pYIei8FI7Q8NW301ukfKXKpeiJ4IPXapeaPXwg==",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            LastChanged = new DateTime(2024, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "AQAAAAIAAYagAAAAEL41Ru8q10GIWJ1/ppnefKNfqqPMsnmeE/fV55Sgysd3HFkzZex9oDJVWsXHFguglg==",
                            Role = "SuperAdmin",
                            UserName = "super"
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PathFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathFotoLarge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathFotoMedium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathFotoSmall")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PembuatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalDiBuat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TanggalDiUbah")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PembuatId");

                    b.ToTable("FotoTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PathFoto = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/pengumuman/natall.jpg",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            PathFoto = "wwwroot/img/pengumuman/rapatt.jpg",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/pengumuman/rapatt.jpg",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            PathFoto = "wwwroot/img/pengumuman/tripp.jpg",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/pengumuman/tripp.jpg",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            PathFoto = "wwwroot/img/pengumuman/donasii.jpg",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/pengumuman/donasii.jpg",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            PathFoto = "wwwroot/img/pengumuman/pelayanann.jpg",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/pengumuman/pelayanann.jpg",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            PathFoto = "wwwroot/img/generaluser.png",
                            PathFotoLarge = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoMedium = "wwwroot/img/pengumuman/natall.jpg",
                            PathFotoSmall = "wwwroot/img/generaluser.png",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Ibadah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsiNasPembimbing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsiRenungan")
                        .HasColumnType("text");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KategoriIbadahId")
                        .HasColumnType("integer");

                    b.Property<string>("NasPembimbing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PendetaId")
                        .HasColumnType("integer");

                    b.Property<string>("Renungan")
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalIbadah")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tempat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KategoriIbadahId");

                    b.HasIndex("PendetaId");

                    b.ToTable("IbadahTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deskripsi = "Kebaktian hari minggu pagi pertama",
                            IsiNasPembimbing = "Isi Naspembimbing",
                            IsiRenungan = "Isi Renungan",
                            Judul = "Kebaktian Pagi Pertama",
                            KategoriIbadahId = 1,
                            NasPembimbing = "Mazmur 12:15",
                            PendetaId = 1,
                            Renungan = "Markus 3:4,15",
                            TanggalIbadah = new DateTime(2024, 6, 23, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Tempat = "Gedung Gereja Ebenhaezer Oeba"
                        },
                        new
                        {
                            Id = 2,
                            Deskripsi = "Kebaktian hari minggu pagi kedua",
                            IsiNasPembimbing = "Isi Naspembimbing",
                            IsiRenungan = "Isi Renungan",
                            Judul = "Kebaktian Pagi Kedua",
                            KategoriIbadahId = 1,
                            NasPembimbing = "Mazmur 12:15",
                            PendetaId = 3,
                            Renungan = "Markus 3:4-15",
                            TanggalIbadah = new DateTime(2024, 6, 23, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Tempat = "Gedung Gereja Ebenhaezer Oeba"
                        },
                        new
                        {
                            Id = 3,
                            Deskripsi = "Perjamuan Bulan Juni",
                            IsiNasPembimbing = "Isi Naspembimbing",
                            Judul = "Perjamuan Bulan Juni",
                            KategoriIbadahId = 2,
                            NasPembimbing = "Matius 3:16",
                            PendetaId = 2,
                            TanggalIbadah = new DateTime(2024, 7, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Tempat = "Gedung Gereja Ebenhaezer Oeba"
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.KategoriIbadah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Durasi")
                        .HasColumnType("interval");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Warna")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("KategoriIbadahTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Durasi = new TimeSpan(0, 2, 0, 0, 0),
                            Nama = "Kebaktian Umum",
                            Warna = -855310
                        },
                        new
                        {
                            Id = 2,
                            Durasi = new TimeSpan(0, 2, 0, 0, 0),
                            Nama = "Perjamuan",
                            Warna = -1180943
                        },
                        new
                        {
                            Id = 3,
                            Durasi = new TimeSpan(0, 2, 0, 0, 0),
                            Nama = "Persiapan Perjamuan",
                            Warna = -331031
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Pendeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacebookProfileLink")
                        .HasColumnType("text");

                    b.Property<int?>("FotoId")
                        .HasColumnType("integer");

                    b.Property<string>("InstagramProfileLink")
                        .HasColumnType("text");

                    b.Property<string>("Jabatan")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeProfileLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("Nama")
                        .IsUnique();

                    b.ToTable("PendetaTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotoId = 6,
                            Nama = "Pendeta 1"
                        },
                        new
                        {
                            Id = 2,
                            FotoId = 6,
                            Nama = "Pendeta 2"
                        },
                        new
                        {
                            Id = 3,
                            FotoId = 6,
                            Nama = "Pendeta 3"
                        },
                        new
                        {
                            Id = 4,
                            FotoId = 6,
                            Nama = "Pendeta 4"
                        },
                        new
                        {
                            Id = 5,
                            FotoId = 6,
                            Nama = "Pendeta 5"
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Pengumuman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FotoId")
                        .HasColumnType("integer");

                    b.Property<bool>("HaveDocument")
                        .HasColumnType("boolean");

                    b.Property<string>("Isi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathPDF")
                        .HasColumnType("text");

                    b.Property<int?>("PembuatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalDiBuat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TanggalDiUbah")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("PembuatId");

                    b.ToTable("PengumumanTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotoId = 1,
                            HaveDocument = false,
                            Isi = "Kami mengundang seluruh jemaat untuk hadir dalam Ibadah Natal yang akan diadakan pada hari Minggu, 25 Desember 2024, pukul 10.00 WIB di Gereja. Mari kita rayakan kelahiran Yesus Kristus dengan sukacita dan kebersamaan. Setelah ibadah, akan diadakan acara ramah tamah di aula gereja.",
                            Judul = "Ibadah Natal Bersama",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            FotoId = 2,
                            HaveDocument = false,
                            Isi = "Rapat Anggota Jemaat Tahunan akan dilaksanakan pada hari Sabtu, 27 Juni 2024, pukul 14.00 WIB di aula gereja. Kami mengajak seluruh jemaat untuk hadir dan berpartisipasi dalam membahas laporan tahunan dan rencana kegiatan gereja untuk tahun 2024.",
                            Judul = "Rapat Anggota Jemaat Tahunan",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            FotoId = 3,
                            HaveDocument = false,
                            Isi = "Kami mengundang para pemuda gereja untuk mengikuti Retret Pemuda yang akan diadakan pada tanggal 15-17 Juli 2024 di Wisma Retreat Agape. Tema retret kali ini adalah \"Membangun Iman yang Kuat di Era Digital\". Pendaftaran dapat dilakukan melalui sekretariat gereja hingga 1 Juli 2024.",
                            Judul = "Retret Pemuda Gereja",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            FotoId = 4,
                            HaveDocument = false,
                            Isi = "Gereja kita akan mengadakan penggalangan dana untuk renovasi bangunan gereja yang direncanakan mulai bulan Juni 2024. Kami mengajak seluruh jemaat untuk berpartisipasi dalam acara ini pada hari Minggu, 5 Juli 2024, pukul 09.00 WIB setelah kebaktian. Donasi dapat diberikan langsung atau melalui rekening gereja.",
                            Judul = "Penggalangan Dana untuk Renovasi Gereja",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            FotoId = 5,
                            HaveDocument = false,
                            Isi = "Dalam rangka menyambut Natal, gereja akan mengadakan kegiatan pelayanan sosial ke Panti Asuhan Kasih Ibu pada hari Sabtu, 23 Desember 2024. Kami mengundang jemaat untuk ikut serta dalam kegiatan ini dengan menyumbangkan pakaian layak pakai, mainan, dan sembako. Barang-barang sumbangan dapat dikumpulkan di kantor gereja hingga 21 Desember 2024.",
                            Judul = "Pelayanan Sosial Natal",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Rayon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FotoKetuaId")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahAnak")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahDewasa")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahLakiLaki")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahLansia")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahPemuda")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahPerempuan")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahRemaja")
                        .HasColumnType("integer");

                    b.Property<string>("KetuaRayon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoWa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FotoKetuaId");

                    b.ToTable("RayonTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E1",
                            Nama = "Rayon E1",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 2,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E2",
                            Nama = "Rayon E2",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 3,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E3",
                            Nama = "Rayon E3",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 4,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E4",
                            Nama = "Rayon E4",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 5,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E5",
                            Nama = "Rayon E5",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 6,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E6",
                            Nama = "Rayon E6",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 7,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E7",
                            Nama = "Rayon E7",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 8,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E8",
                            Nama = "Rayon E8",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 9,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E9",
                            Nama = "Rayon E9",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 10,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E10",
                            Nama = "Rayon E10",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 11,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E11",
                            Nama = "Rayon E11",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 12,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E12",
                            Nama = "Rayon E12",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 13,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E13",
                            Nama = "Rayon E13",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 14,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E14",
                            Nama = "Rayon E14",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 15,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E15",
                            Nama = "Rayon E15",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 16,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E16",
                            Nama = "Rayon E16",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 17,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E17",
                            Nama = "Rayon E17",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 18,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E18",
                            Nama = "Rayon E18",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 19,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E19",
                            Nama = "Rayon E19",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 20,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E20",
                            Nama = "Rayon E20",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 21,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E21",
                            Nama = "Rayon E21",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 22,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E22",
                            Nama = "Rayon E22",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 23,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E23",
                            Nama = "Rayon E23",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 24,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E24",
                            Nama = "Rayon E24",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 25,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E25",
                            Nama = "Rayon E25",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 26,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E26",
                            Nama = "Rayon E26",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 27,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E27",
                            Nama = "Rayon E27",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 28,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E28",
                            Nama = "Rayon E28",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 29,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E29",
                            Nama = "Rayon E29",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 30,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E30",
                            Nama = "Rayon E30",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 31,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E31",
                            Nama = "Rayon E31",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 32,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E32",
                            Nama = "Rayon E32",
                            NoWa = "081234567891"
                        },
                        new
                        {
                            Id = 33,
                            FotoKetuaId = 6,
                            JumlahAnak = 10,
                            JumlahDewasa = 15,
                            JumlahLakiLaki = 25,
                            JumlahLansia = 15,
                            JumlahPemuda = 10,
                            JumlahPerempuan = 35,
                            JumlahRemaja = 10,
                            KetuaRayon = "Ketua Rayon E33",
                            Nama = "Rayon E33",
                            NoWa = "081234567891"
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.WartaJemaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PembuatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TanggalDiBuat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TanggalDiUbah")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("TanggalWarta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PembuatId");

                    b.HasIndex("TanggalWarta");

                    b.ToTable("WartaJemaatTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentLink = "https://drive.google.com/file/d/1-O8JJyBhEPPhwjjGKQp9u2gur0gWxuSl/view?usp=sharing",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalWarta = new DateOnly(2024, 7, 7)
                        },
                        new
                        {
                            Id = 2,
                            DocumentLink = "https://drive.google.com/file/d/1-O8JJyBhEPPhwjjGKQp9u2gur0gWxuSl/view?usp=sharing",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalWarta = new DateOnly(2024, 7, 21)
                        },
                        new
                        {
                            Id = 3,
                            DocumentLink = "https://drive.google.com/file/d/1-O8JJyBhEPPhwjjGKQp9u2gur0gWxuSl/view?usp=sharing",
                            PembuatId = 1,
                            TanggalDiBuat = new DateTime(2024, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalWarta = new DateOnly(2024, 7, 28)
                        });
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Foto", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.AppUser", "Pembuat")
                        .WithMany()
                        .HasForeignKey("PembuatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pembuat");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Ibadah", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.KategoriIbadah", "KategoriIbadah")
                        .WithMany("DaftarIbadah")
                        .HasForeignKey("KategoriIbadahId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.Pendeta", "Pendeta")
                        .WithMany("DaftarIbadah")
                        .HasForeignKey("PendetaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KategoriIbadah");

                    b.Navigation("Pendeta");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Pendeta", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Pengumuman", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.AppUser", "Pembuat")
                        .WithMany()
                        .HasForeignKey("PembuatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Foto");

                    b.Navigation("Pembuat");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Rayon", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.Foto", "FotoKetua")
                        .WithMany()
                        .HasForeignKey("FotoKetuaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FotoKetua");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.WartaJemaat", b =>
                {
                    b.HasOne("PKMGerejaEbenhaezer.Domain.Entity.AppUser", "Pembuat")
                        .WithMany()
                        .HasForeignKey("PembuatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pembuat");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.KategoriIbadah", b =>
                {
                    b.Navigation("DaftarIbadah");
                });

            modelBuilder.Entity("PKMGerejaEbenhaezer.Domain.Entity.Pendeta", b =>
                {
                    b.Navigation("DaftarIbadah");
                });
#pragma warning restore 612, 618
        }
    }
}
